# Generated by Django 2.2.3 on 2019-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
